export enum ROUTES {
  APP_NAVIGATION = 'APP_NAVIGATION',
  GUEST_NAVIGATION = 'GUEST_NAVIGATION',
}

export enum EGuestScreenList {
  SIGN_UP_SCREEN = 'SIGN_UP_SCREEN',
  SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',
  FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN',
  CHANGE_PASSWORD_SCREEN = 'CHANGE_PASSWORD_SCREEN',
}

export enum EAppScreenList {
  HOME_STACK_SCREEN = 'HOME_STACK_SCREEN',
  EVENT_STACK_SCREEN = 'EVENT_STACK_SCREEN',
  NOTIFICATION_STACK_SCREEN = 'NOTIFICATION_STACK_SCREEN',
  SETTING_STACK_SCREEN = 'SETTING_STACK_SCREEN',
  ADD_EVENT_STACK_SCREEN = 'ADD_EVENT_STACK_SCREEN',
}

export enum EHomeScreenList {
  HOME_SCREEN = 'HOME_SCREEN',
  EVENT_DETAIL_SCREEN = 'EVENT_DETAIL_SCREEN',
}

export enum EventScreenList {
  EVENT_DETAIL_SCREEN = 'EVENT_DETAIL_SCREEN',
}

export enum ESettingScreenList {
  EVENT_DETAIL_SCREEN = 'EVENT_DETAIL_SCREEN',
}
