export enum ROUTES {
  APP_NAVIGATION = 'APP_NAVIGATION',
  GUEST_NAVIGATION = 'GUEST_NAVIGATION',
}

export enum EGuestScreenList {
  SIGN_UP = 'SIGN_UP',
  LOG_IN = 'LOG_IN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
}

export enum EAppScreenList {
  HOME_STACK_SCREEN = 'HOME_STACK_SCREEN',
  EVENT_STACK_SCREEN = 'EVENT_STACK_SCREEN',
  NOTIFICATION_STACK_SCREEN = 'NOTIFICATION_STACK_SCREEN',
  SETTING_STACK_SCREEN = 'SETTING_STACK_SCREEN',
  ADD_EVENT_STACK_SCREEN = 'ADD_EVENT_STACK_SCREEN',
}

export enum EHomeScreenList {
  HOME_SCREEN = 'HOME_SCREEN',
  EVENT_DETAIL_SCREEN = 'EVENT_DETAIL_SCREEN',
}

export enum EventScreenList {
  EVENT_DETAIL_SCREEN = 'EVENT_DETAIL_SCREEN',
}

export enum ESettingScreenList {
  EVENT_DETAIL_SCREEN = 'EVENT_DETAIL_SCREEN',
}
